export const randomData = [
  {
    id: 3,
    kullaniciAdi: "john_doe",
    ad: "John",
    yetki: "Yonetici",
    soyad: "Doe",
    aciklama: "Lorem ipsum dolor sit amet",
    ePosta: "john.doe@example.com",
    telefon: "555-555-5555",
    onayliMi: true,
    kilitliMi: false,
    sifre: "123123123",
  },
  {
    id: 2,
    kullaniciAdi: "jane_smith",
    ad: "Jane",
    yetki: "Yonetici",
    soyad: "Smith",
    aciklama: "Consectetur adipiscing elit",
    ePosta: "jane.smith@example.com",
    telefon: "555-123-4567",
    onayliMi: false,
    kilitliMi: true,
    sifre: "123123123",
  },
  {
    kullaniciAdi: "alice_miller",
    id: 1,
    ad: "Alice",
    yetki: "Ozel Kullanici",
    soyad: "Miller",
    aciklama: "Sed do eiusmod tempor ",
    ePosta: "alice.miller@example.com",
    telefon: "555-987-6543",
    onayliMi: true,
    kilitliMi: false,
    sifre: "123123123",
  },
];

export const customersData = [
  {
    customerName: "ABC Company",
    location: "Istanbul",
    contactFirstName: "Ahmet",
    contactLastName: "Yilmaz",
    contactTcNo: "12345678901",
    contactEmail: "ahmet@example.com",
    contactPhone: "5551234567",
    address: "Sample Neighborhood, Sample Street No: 1",
    description: "Tasks with ABC Company",
    actions: "",
  },
  {
    customerName: "DEF Ltd.",
    location: "Ankara",
    contactFirstName: "Ayse",
    contactLastName: "Kaya",
    contactTcNo: "23456789012",
    contactEmail: "ayse@example.com",
    contactPhone: "5552345678",
    address: "Sample Neighborhood, Sample Street No: 2",
    description: "Tasks with DEF Ltd.",
    actions: "",
  },
  {
    customerName: "GHI Inc.",
    location: "Izmir",
    contactFirstName: "Mehmet",
    contactLastName: "Demir",
    contactTcNo: "34567890123",
    contactEmail: "mehmet@example.com",
    contactPhone: "5553456789",
    address: "Sample Neighborhood, Sample Street No: 3",
    description: "Tasks with GHI Inc.",
    actions: "",
  },
  {
    customerName: "JKL Technology",
    location: "Bursa",
    contactFirstName: "Fatma",
    contactLastName: "Kara",
    contactTcNo: "45678901234",
    contactEmail: "fatma@example.com",
    contactPhone: "5554567890",
    address: "Sample Neighborhood, Sample Street No: 4",
    description: "Tasks with JKL Technology",
    actions: "",
  },
  {
    customerName: "MNO Consulting",
    location: "Istanbul",
    contactFirstName: "Ali",
    contactLastName: "Yildiz",
    contactTcNo: "56789012345",
    contactEmail: "ali@example.com",
    contactPhone: "5555678901",
    address: "Sample Neighborhood, Sample Street No: 5",
    description: "Tasks with MNO Consulting",
    actions: "",
  },
  {
    customerName: "PQR Ltd.",
    location: "Ankara",
    contactFirstName: "Zeynep",
    contactLastName: "Yilmaz",
    contactTcNo: "67890123456",
    contactEmail: "zeynep@example.com",
    contactPhone: "5556789012",
    address: "Sample Neighborhood, Sample Street No: 6",
    description: "Tasks with PQR Ltd.",
    actions: "",
  },
  {
    customerName: "STU Construction",
    location: "Izmir",
    contactFirstName: "Emre",
    contactLastName: "Demir",
    contactTcNo: "78901234567",
    contactEmail: "emre@example.com",
    contactPhone: "5557890123",
    address: "Sample Neighborhood, Sample Street No: 7",
    description: "Tasks with STU Construction",
    actions: "",
  },
  {
    customerName: "VWX Ltd.",
    location: "Bursa",
    contactFirstName: "Cem",
    contactLastName: "Kara",
    contactTcNo: "89012345678",
    contactEmail: "cem@example.com",
    contactPhone: "5558901234",
    address: "Sample Neighborhood, Sample Street No: 8",
    description: "Tasks with VWX Ltd.",
    actions: "",
  },
  {
    customerName: "YZX Consulting",
    location: "Istanbul",
    contactFirstName: "Zehra",
    contactLastName: "Yildiz",
    contactTcNo: "90123456789",
    contactEmail: "zehra@example.com",
    contactPhone: "5559012345",
    address: "Sample Neighborhood, Sample Street No: 9",
    description: "Tasks with YZX Consulting",
    actions: "",
  },
  {
    customerName: "EXAMPLE Company",
    location: "Ankara",
    contactFirstName: "Kemal",
    contactLastName: "Yilmaz",
    contactTcNo: "01234567890",
    contactEmail: "kemal@example.com",
    contactPhone: "5550123456",
    address: "Sample Neighborhood, Sample Street No: 10",
    description: "Tasks with EXAMPLE Company",
    actions: "",
  },
];
